<?php

namespace SocialLibrary\ReadableMedia\MangaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MangaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MangaRepository extends EntityRepository
{
    public function findAllPaginated($paginator, $page)
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT m, s, c FROM SocialLibraryReadableMediaMangaBundle:Manga m
                    JOIN m.serie s
                    JOIN m.creators c');
        
        try {
            return $paginator->paginate($query, $page);
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
    public function findManga($id, $nameSlug)
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT m, s, c FROM SocialLibraryReadableMediaMangaBundle:Manga m
                    JOIN m.serie s
                    JOIN m.creators c
                    WHERE m.id = :id AND m.nameSlug = :nameSlug')
            ->setParameter('id', $id)
            ->setParameter('nameSlug', $nameSlug);
        
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
