_welcome:
    resource: "@SocialLibraryBaseBundle/Resources/config/routing/welcome.xml"
    pattern:  /

social_library_read_serie:
    resource: "@SocialLibraryReadBundle/Resources/config/routing/serie.xml"
    prefix:   /read-serie

social_library_readable_media_manga:
    resource: "@SocialLibraryReadBundleMangaBundle/Resources/config/routing/manga.xml"
    prefix:   /manga

social_library_readable_media_novel:
    resource: "@SocialLibraryReadBundle/Resources/config/routing/novel.xml"
    prefix:   /novel

social_library_readable_media_graphic_novel:
    resource: "@SocialLibraryReadBundle/Resources/config/routing/graphic_novel.xml"
    prefix:   /graphic-novel

social_library_base_object_creator:
    resource: "@SocialLibraryBaseBundle/Resources/config/routing/object_creator.xml"
    prefix: /object-creator

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

sonata_page_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media



