<?php

namespace SocialLibrary\ReadableMedia\NovelBundle\Entity;

use Application\Sonata\UserBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * NovelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NovelRepository extends EntityRepository
{
    public function findAllPaginated($paginator, $page, User $user = null)
    {
        $query = $this
            ->getEntityManager()
            ->createQueryBuilder()
            ->select(array('n', 's', 'c', 'o'))
            ->from('SocialLibraryReadableMediaNovelBundle:Novel', 'n')
            ->leftJoin('n.serie', 's')
            ->innerJoin('n.creators', 'c')
            ->leftJoin('n.owners', 'o')
            ->orderBy('n.volume');
        
        if($user != null) {
            $query = $query
                ->where('o.usernameCanonical = :username')
                ->setParameter('username', $user->getUsernameCanonical());
        }
        
        try {
            return $paginator->paginate($query, $page);
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
    public function findNovel($id, $nameSlug)
    {
        $query = $this->getEntityManager()
            ->createQueryBuilder()
            ->select(array('n', 's', 'c', 'o'))
            ->from('SocialLibraryReadableMediaNovelBundle:Novel', 'n')
            ->leftJoin('n.serie', 's')
            ->innerJoin('n.creators', 'c')
            ->leftJoin('n.owners', 'o')
            ->where('n.id = :id')
            ->andWhere('n.nameSlug = :nameSlug')
            ->setParameter('id', $id)
            ->setParameter('nameSlug', $nameSlug)
            ->getQuery();
        
        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
